In [ ]:
# 1. Create a scalar tensor with value 10 using tf.constant and print its value and data type.
import tensorflow as tf
scalar = tf.constant(10)
print(scalar)


tf.Tensor(10, shape=(), dtype=int32)


In [ ]:
# 2. Create a 1-D tensor (vector) [2, 4, 6, 8] using tf.constant and print its shape and numpy value.

vector = tf.constant([2, 4, 6, 8])
print(vector.numpy())
print(vector.shape)

[2 4 6 8]
(4,)


In [ ]:
# 3. Create a 2-D tensor (matrix) [[1, 2], [3, 4]] using tf.constant and print its shape and dtype.

matrix = tf.constant([[1, 2], [3, 4]])
print(matrix)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [ ]:
# 4. Create a tf.Variable with initial value 5.0 and print its current value.
variable = tf.Variable(5.0)
print(variable.numpy())

5.0


In [ ]:

# 5. Update the above variable by assigning it a new value 10.0 using assign() and print the updated value.

variable = tf.Variable(5.0)
variable.assign(10.0)
print(variable.numpy())

10.0


In [ ]:
# 6. Use assign_add() on a variable initialized with [[1.0, 2.0], [3.0, 4.0]] to add 1.0 to every element and print the result.
variable = tf.Variable([[1.0, 2.0], [3.0, 4.0]])
hello=variable.assign_add([[1.0,1.0],[1.0,1.0]])
print(hello.numpy())


[[2. 3.]
 [4. 5.]]


In [ ]:

# 9. Create two constant tensors a = [[1, 2], [3, 4]] and b = [[5, 6], [7, 8]] and perform matrix multiplication using tf.matmul().

a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])
c=tf.matmul(a,b)
print(c.numpy())

[[19 22]
 [43 50]]


In [ ]:
# 10. Create a random tensor of shape (3, 3) using tf.random.uniform() and print its shape, dtype, and values.

random_tensor = tf.random.uniform(shape=(3, 3))
print(random_tensor)

tf.Tensor(
[[0.5239152  0.630901   0.10795653]
 [0.55679655 0.19220817 0.18186235]
 [0.04964638 0.06650543 0.9821141 ]], shape=(3, 3), dtype=float32)
